version: '3'

services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: wwchacalww/node_mysql:latest
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh node index.js
    networks:
      - node_nginx
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node_nginx
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_nginx

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: wwchacalww/nginx_node:latest
    container_name: nginx
    networks:
      - node_nginx
    ports:
      - "8080:80"
    depends_on:
      - node

networks:
  node_nginx:
    driver: bridge
